import { describe, expect, it } from "vitest";
import {
  appendHeaders,
  generateAssetsIgnore,
  generateHeaders,
  generateRedirects,
  generateWorkerShim,
  makeStubEmulator,
} from "../src/index.ts";

describe("generateWorkerShim", () => {
  const shim = generateWorkerShim({
    serverImport: "./../output/server/index.js",
    manifestImport: "./../cloudflare-tmp/manifest.js",
    assetsBinding: "ASSETS",
  });

  it("imports the server and manifest through real relative paths", () => {
    expect(shim).toContain(`import { Server } from "./../output/server/index.js";`);
    expect(shim).toContain(
      `import { manifest, prerendered, base_path } from "./../cloudflare-tmp/manifest.js";`,
    );
  });

  it("uses module-level env from cloudflare:workers", () => {
    expect(shim).toContain(`import { env } from 'cloudflare:workers';`);
  });

  it("serves static and prerendered files through the assets binding", () => {
    expect(shim).toContain("env.ASSETS.fetch(req)");
    expect(shim).toContain("env.ASSETS.fetch(url)");
  });

  it("respects a custom assets binding name", () => {
    const custom = generateWorkerShim({
      serverImport: "./server/index.js",
      manifestImport: "./manifest.js",
      assetsBinding: "STATIC",
    });
    expect(custom).toContain("env.STATIC.fetch(req)");
    expect(custom).not.toContain("env.ASSETS.fetch");
  });

  it("replaces worktop with a caches.default pragma cache", () => {
    expect(shim).not.toContain("worktop");
    expect(shim).toContain("caches.default");
    expect(shim).toContain("cache_lookup");
    expect(shim).toContain("cache_save");
  });

  it("exposes the platform to server.respond", () => {
    expect(shim).toContain("platform: { env, ctx, caches, cf: req.cf }");
  });
});

describe("appendHeaders", () => {
  it("adds a new rule block", () => {
    const content = appendHeaders("/_app/*", ["X-Robots-Tag: noindex"], "");
    expect(content).toContain("/_app/*\n  X-Robots-Tag: noindex");
    expect(content).toContain("AUTOGENERATED SVELTE IMMUTABLE HEADERS");
  });

  it("merges into an existing block for the same URL", () => {
    const existing = "/_app/*\n  X-Existing: yes";
    const content = appendHeaders("/_app/*", ["X-Robots-Tag: noindex"], existing);
    expect(content).toBe("/_app/*\n  X-Robots-Tag: noindex\n  X-Existing: yes");
  });
});

describe("generateHeaders", () => {
  it("emits noindex and immutable cache rules for the app dir", () => {
    const content = generateHeaders("_app");
    expect(content).toContain("/_app/*\n  X-Robots-Tag: noindex\n  Cache-Control: no-cache");
    expect(content).toContain(
      "/_app/immutable/*\n  ! Cache-Control\n  Cache-Control: public, immutable, max-age=31536000",
    );
  });

  it("preserves user-authored headers", () => {
    const content = generateHeaders("_app", "/api/*\n  X-Fixture: yes");
    expect(content).toContain("/api/*\n  X-Fixture: yes");
    expect(content).toContain("/_app/immutable/*");
  });
});

describe("generateRedirects", () => {
  it("returns undefined when there is nothing to write", () => {
    expect(generateRedirects(new Map())).toBeUndefined();
  });

  it("emits prerendered redirect rules", () => {
    const content = generateRedirects(new Map([["/old", { status: 301, location: "/new" }]]));
    expect(content).toContain("/old /new 301");
    expect(content).toContain("AUTOGENERATED SVELTE PRERENDERED REDIRECTS");
  });

  it("prepends user-authored redirects", () => {
    const content = generateRedirects(
      new Map([["/old", { status: 301, location: "/new" }]]),
      "/legacy /modern 302",
    );
    expect(content?.startsWith("/legacy /modern 302")).toBe(true);
    expect(content).toContain("/old /new 301");
  });
});

describe("generateAssetsIgnore", () => {
  it("excludes the worker entry and metadata files from assets", () => {
    const content = generateAssetsIgnore();
    expect(content.split("\n").filter(Boolean)).toEqual([
      "_worker.js",
      "_routes.json",
      "_headers",
      "_redirects",
    ]);
  });
});

describe("makeStubEmulator", () => {
  it("exposes env values and a no-op ctx outside prerendering", async () => {
    const emulator = makeStubEmulator({ SECRET: "value" });
    const platform = (await emulator.platform?.({ config: {}, prerender: false })) as {
      env: Record<string, unknown>;
      ctx: { waitUntil: (promise: Promise<unknown>) => void };
      caches: { default: { match: () => Promise<undefined> } };
      cf: Record<string, unknown>;
    };
    expect(platform.env["SECRET"]).toBe("value");
    expect(() => platform.ctx.waitUntil(Promise.resolve())).not.toThrow();
    await expect(platform.caches.default.match()).resolves.toBeUndefined();
    expect(platform.cf).toEqual({});
  });

  it("throws on env access in prerenderable routes", async () => {
    const emulator = makeStubEmulator({ SECRET: "value" });
    const platform = (await emulator.platform?.({ config: {}, prerender: true })) as {
      env: Record<string, unknown>;
    };
    expect(() => platform.env["SECRET"]).toThrow(
      "Cannot access platform.env.SECRET in a prerenderable route",
    );
  });
});
